Feature/preprocessing
phipag/PDS_Project pull request #2
Opened 2020-05-04 15:18 UTC by phipag

I finished the first part of the project. Please leave me some feedback.

2020-05-04 15:25 UTC, LHumpe commented
Please omit printing of first line in Jupyter notebook

2020-05-04 15:51 UTC, LHumpe commented
Please comment all Classes and Functions properly:
Example:

```
class Transformer(AbstractValidator):
    """
    A class that inherits from AbstractValidator handling xyz
    """
    __preprocessor: Preprocessor
    __gdf: gpd.GeoDataFrame = None

    @property
    def gdf(self) -> gpd.GeoDataFrame:
        """
        Does not need an import param
        :return: a Geodataframe containing information xyz
        """
        if self.__gdf is None:
            raise UserWarning('Data frame is not initialized.')
        return self.__gdf

    def __init__(self, preprocessor: Preprocessor):
        """
        Function for initialising the preprocessor class
        :param preprocessor: the class preprocessor
        """
        try:
            if preprocessor.validate():
                self.__preprocessor = preprocessor
        except ValueError:
            raise ValueError('Preprocessor validation failed. Please make sure that the Preprocessor was successful.')```

2020-05-05 07:28 UTC, LHumpe requested changes
Please comment all Classes and Functions properly:
Example:

```
class Transformer(AbstractValidator):
    """
    A class that inherits from AbstractValidator handling xyz
    """
    __preprocessor: Preprocessor
    __gdf: gpd.GeoDataFrame = None

    @property
    def gdf(self) -> gpd.GeoDataFrame:
        """
        Does not need an import param
        :return: a Geodataframe containing information xyz
        """
        if self.__gdf is None:
            raise UserWarning('Data frame is not initialized.')
        return self.__gdf

    def __init__(self, preprocessor: Preprocessor):
        """
        Function for initialising the preprocessor class
        :param preprocessor: the class preprocessor
        """
        try:
            if preprocessor.validate():
                self.__preprocessor = preprocessor
        except ValueError:
            raise ValueError('Preprocessor validation failed. Please make sure that the Preprocessor was successful.')```

2020-05-05 07:46 UTC, LHumpe commented on nextbike/preprocessing/Transformer.py
> +    def transform(self, validate=False) -> None:
Add dummy variable is_station utilising p_place_type

Keep station names for start and end 

Duration as float or int

2020-05-05 08:14 UTC, LHumpe commented on nextbike/preprocessing/Transformer.py
> +    def transform(self, validate=False) -> None:
Add columns month_of_year, day_of_week(weekday), hour_of_day

2020-05-07 12:29 UTC, phipag commented
> Please omit printing of first line in Jupyter notebook

I don't think this is a good idea because the user wants to see if the package could be installed correctly.

2020-05-07 12:29 UTC, phipag commented
> Please comment all Classes and Functions properly:
> Example:
> 
> ```
> class Transformer(AbstractValidator):
>     """
>     A class that inherits from AbstractValidator handling xyz
>     """
>     __preprocessor: Preprocessor
>     __gdf: gpd.GeoDataFrame = None
> 
>     @property
>     def gdf(self) -> gpd.GeoDataFrame:
>         """
>         Does not need an import param
>         :return: a Geodataframe containing information xyz
>         """
>         if self.__gdf is None:
>             raise UserWarning('Data frame is not initialized.')
>         return self.__gdf
> 
>     def __init__(self, preprocessor: Preprocessor):
>         """
>         Function for initialising the preprocessor class
>         :param preprocessor: the class preprocessor
>         """
>         try:
>             if preprocessor.validate():
>                 self.__preprocessor = preprocessor
>         except ValueError:
>             raise ValueError('Preprocessor validation failed. Please make sure that the Preprocessor was successful.')```
> ```

Done by a3fd9c90

2020-05-07 13:06 UTC, phipag commented on nextbike/preprocessing/Transformer.py
> +    def transform(self, validate=False) -> None:
Done by 4bc6453f

2020-05-07 15:08 UTC, LHumpe reviewed
Well done Philipp! Thank you

2020-05-07 15:08 UTC, LHumpe approved these changes

2020-05-07 15:09 UTC, merged